package rs.sergioribera.notinplus

import android.app.NativeActivity
import android.os.Bundle
import rs.sergioribera.notinplus.gen.IstmoPluginRegistry
import dev.istmo.runtime.IstmoRuntime

// NativeActivity subclass that boots IstmoRuntime and wires every plugin
// dispatcher generated by `istmo_build::emit()` — one call, all plugins.
class NotinplusActivity : NativeActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        IstmoRuntime.instance.start(this)

        // Registers every plugin whose `istmo.toml` declares
        // `auto_register = true` (the default). Plugins with a bespoke
        // constructor opt out and are registered manually here.
        IstmoPluginRegistry.registerAll(applicationContext)

        super.onCreate(savedInstanceState)
    }
}
