// GENERATED by istmo-build - DO NOT EDIT.
// Registers every plugin dispatcher whose backend follows the
// default construction convention `<T>BackendImpl()`. Plugins with
// bespoke construction opt out via `auto_register = false` in
// `istmo.toml`.

import Foundation
import IstmoRuntime

enum IstmoPluginRegistry {
    static func registerAll(runtime: IstmoRuntime = .shared) {
        // No auto-registerable plugins in this build.
    }
}
