package dev.istmo.runtime

// GENERATED by istmo-build - DO NOT EDIT.
// Registers every plugin dispatcher whose backend follows the
// default construction convention `<T>BackendImpl(context)`. Plugins
// with bespoke construction opt out via `auto_register = false` in
// `istmo.toml`.

import android.content.Context
import dev.istmo.runtime.IstmoRuntime

object IstmoPluginRegistry {
    fun registerAll(context: Context, runtime: IstmoRuntime = IstmoRuntime) {
        // No auto-registerable plugins in this build.
    }
}
