package dev.istmo.runtime

import kotlinx.coroutines.flow.map

// GENERATED by istmo-build - DO NOT EDIT.
// plugin id: istmo.pen
import java.io.ByteArrayOutputStream

class PenCodecsImpl : PenCodecs {

    override fun readPenConfig(bytes: ByteArray, offset: Int): Bincode.Decoded<PenConfig> {
        var cursor = offset
        val d_windowId = Bincode.readVarintU64(bytes, cursor).let { Bincode.Decoded(it.value.toULong(), it.consumed) }
        cursor = d_windowId.consumed
        val windowId = d_windowId.value
        return Bincode.Decoded(PenConfig(windowId = windowId), cursor)
    }

    override fun writePenConfig(out: ByteArrayOutputStream, value: PenConfig) {
        Bincode.writeVarintU64(out, value.windowId.toLong())
    }

    override fun readPenToolKind(bytes: ByteArray, offset: Int): Bincode.Decoded<PenToolKind> {
        val d = Bincode.readVarintU64(bytes, offset)
        val variant = PenToolKind.entries.getOrNull(d.value.toInt())
            ?: error("PenToolKind: unknown discriminant ${d.value}")
        return Bincode.Decoded(variant, d.consumed)
    }

    override fun writePenToolKind(out: ByteArrayOutputStream, value: PenToolKind) {
        Bincode.writeEnumDiscriminant(out, value.ordinal)
    }

    override fun readPenSample(bytes: ByteArray, offset: Int): Bincode.Decoded<PenSample> {
        var cursor = offset
        val d_x = Bincode.readF32(bytes, cursor)
        cursor = d_x.consumed
        val x = d_x.value
        val d_y = Bincode.readF32(bytes, cursor)
        cursor = d_y.consumed
        val y = d_y.value
        val d_pressure = Bincode.readF32(bytes, cursor)
        cursor = d_pressure.consumed
        val pressure = d_pressure.value
        val d_tiltX = Bincode.readF32(bytes, cursor)
        cursor = d_tiltX.consumed
        val tiltX = d_tiltX.value
        val d_tiltY = Bincode.readF32(bytes, cursor)
        cursor = d_tiltY.consumed
        val tiltY = d_tiltY.value
        val d_azimuth = Bincode.readF32(bytes, cursor)
        cursor = d_azimuth.consumed
        val azimuth = d_azimuth.value
        val d_altitude = Bincode.readF32(bytes, cursor)
        cursor = d_altitude.consumed
        val altitude = d_altitude.value
        val d_twist = Bincode.readF32(bytes, cursor)
        cursor = d_twist.consumed
        val twist = d_twist.value
        val d_tangentialPressure = Bincode.readF32(bytes, cursor)
        cursor = d_tangentialPressure.consumed
        val tangentialPressure = d_tangentialPressure.value
        val d_zOffset = Bincode.readF32(bytes, cursor)
        cursor = d_zOffset.consumed
        val zOffset = d_zOffset.value
        val d_timestampUs = Bincode.readVarintU64(bytes, cursor).let { Bincode.Decoded(it.value.toULong(), it.consumed) }
        cursor = d_timestampUs.consumed
        val timestampUs = d_timestampUs.value
        val d_sequence = Bincode.readVarintU64(bytes, cursor).let { Bincode.Decoded(it.value.toUInt(), it.consumed) }
        cursor = d_sequence.consumed
        val sequence = d_sequence.value
        val d_toolId = Bincode.readVarintU64(bytes, cursor).let { Bincode.Decoded(it.value.toUInt(), it.consumed) }
        cursor = d_toolId.consumed
        val toolId = d_toolId.value
        val d_toolKind = readPenToolKind(bytes, cursor)
        cursor = d_toolKind.consumed
        val toolKind = d_toolKind.value
        val d_buttons = Bincode.readVarintU64(bytes, cursor).let { Bincode.Decoded(it.value.toUInt(), it.consumed) }
        cursor = d_buttons.consumed
        val buttons = d_buttons.value
        return Bincode.Decoded(PenSample(x = x, y = y, pressure = pressure, tiltX = tiltX, tiltY = tiltY, azimuth = azimuth, altitude = altitude, twist = twist, tangentialPressure = tangentialPressure, zOffset = zOffset, timestampUs = timestampUs, sequence = sequence, toolId = toolId, toolKind = toolKind, buttons = buttons), cursor)
    }

    override fun writePenSample(out: ByteArrayOutputStream, value: PenSample) {
        Bincode.writeF32(out, value.x)
        Bincode.writeF32(out, value.y)
        Bincode.writeF32(out, value.pressure)
        Bincode.writeF32(out, value.tiltX)
        Bincode.writeF32(out, value.tiltY)
        Bincode.writeF32(out, value.azimuth)
        Bincode.writeF32(out, value.altitude)
        Bincode.writeF32(out, value.twist)
        Bincode.writeF32(out, value.tangentialPressure)
        Bincode.writeF32(out, value.zOffset)
        Bincode.writeVarintU64(out, value.timestampUs.toLong())
        Bincode.writeVarintU64(out, value.sequence.toLong())
        Bincode.writeVarintU64(out, value.toolId.toLong())
        writePenToolKind(out, value.toolKind)
        Bincode.writeVarintU64(out, value.buttons.toLong())
    }

    override fun readPenMove(bytes: ByteArray, offset: Int): Bincode.Decoded<PenMove> {
        var cursor = offset
        val d_sample = readPenSample(bytes, cursor)
        cursor = d_sample.consumed
        val sample = d_sample.value
        val d_coalesced = Bincode.readVec(bytes, cursor) { p, o -> readPenSample(p, o) }
        cursor = d_coalesced.consumed
        val coalesced = d_coalesced.value
        val d_predicted = Bincode.readVec(bytes, cursor) { p, o -> readPenSample(p, o) }
        cursor = d_predicted.consumed
        val predicted = d_predicted.value
        return Bincode.Decoded(PenMove(sample = sample, coalesced = coalesced, predicted = predicted), cursor)
    }

    override fun writePenMove(out: ByteArrayOutputStream, value: PenMove) {
        writePenSample(out, value.sample)
        Bincode.writeVec(out, value.coalesced) { s, v -> writePenSample(s, v) }
        Bincode.writeVec(out, value.predicted) { s, v -> writePenSample(s, v) }
    }

    override fun readPenButtonChange(bytes: ByteArray, offset: Int): Bincode.Decoded<PenButtonChange> {
        var cursor = offset
        val d_sample = readPenSample(bytes, cursor)
        cursor = d_sample.consumed
        val sample = d_sample.value
        val d_changed = Bincode.readVarintU64(bytes, cursor).let { Bincode.Decoded(it.value.toUInt(), it.consumed) }
        cursor = d_changed.consumed
        val changed = d_changed.value
        return Bincode.Decoded(PenButtonChange(sample = sample, changed = changed), cursor)
    }

    override fun writePenButtonChange(out: ByteArrayOutputStream, value: PenButtonChange) {
        writePenSample(out, value.sample)
        Bincode.writeVarintU64(out, value.changed.toLong())
    }

    override fun readPenEvent(bytes: ByteArray, offset: Int): Bincode.Decoded<PenEvent> {
        var cursor = offset
        val disc = Bincode.readVarintU64(bytes, cursor)
        cursor = disc.consumed
        return when (disc.value.toInt()) {
            0 -> {
                val d_inner = readPenSample(bytes, cursor)
                cursor = d_inner.consumed
                val inner = d_inner.value
                Bincode.Decoded(PenEvent.Down(inner) as PenEvent, cursor)
            }
            1 -> {
                val d_inner = readPenMove(bytes, cursor)
                cursor = d_inner.consumed
                val inner = d_inner.value
                Bincode.Decoded(PenEvent.Move(inner) as PenEvent, cursor)
            }
            2 -> {
                val d_inner = readPenSample(bytes, cursor)
                cursor = d_inner.consumed
                val inner = d_inner.value
                Bincode.Decoded(PenEvent.Up(inner) as PenEvent, cursor)
            }
            3 -> {
                val d_inner = readPenSample(bytes, cursor)
                cursor = d_inner.consumed
                val inner = d_inner.value
                Bincode.Decoded(PenEvent.Cancel(inner) as PenEvent, cursor)
            }
            4 -> {
                val d_inner = readPenButtonChange(bytes, cursor)
                cursor = d_inner.consumed
                val inner = d_inner.value
                Bincode.Decoded(PenEvent.ButtonChanged(inner) as PenEvent, cursor)
            }
            else -> error("PenEvent: unknown discriminant ${disc.value}")
        }
    }

    override fun writePenEvent(out: ByteArrayOutputStream, value: PenEvent) {
        when (value) {
            is PenEvent.Down -> {
                Bincode.writeEnumDiscriminant(out, 0)
                writePenSample(out, value.value)
            }
            is PenEvent.Move -> {
                Bincode.writeEnumDiscriminant(out, 1)
                writePenMove(out, value.value)
            }
            is PenEvent.Up -> {
                Bincode.writeEnumDiscriminant(out, 2)
                writePenSample(out, value.value)
            }
            is PenEvent.Cancel -> {
                Bincode.writeEnumDiscriminant(out, 3)
                writePenSample(out, value.value)
            }
            is PenEvent.ButtonChanged -> {
                Bincode.writeEnumDiscriminant(out, 4)
                writePenButtonChange(out, value.value)
            }
        }
    }

    override fun readPenHoverEvent(bytes: ByteArray, offset: Int): Bincode.Decoded<PenHoverEvent> {
        var cursor = offset
        val disc = Bincode.readVarintU64(bytes, cursor)
        cursor = disc.consumed
        return when (disc.value.toInt()) {
            0 -> {
                val d_inner = readPenSample(bytes, cursor)
                cursor = d_inner.consumed
                val inner = d_inner.value
                Bincode.Decoded(PenHoverEvent.ProximityEnter(inner) as PenHoverEvent, cursor)
            }
            1 -> {
                val d_inner = readPenSample(bytes, cursor)
                cursor = d_inner.consumed
                val inner = d_inner.value
                Bincode.Decoded(PenHoverEvent.Move(inner) as PenHoverEvent, cursor)
            }
            2 -> Bincode.Decoded(PenHoverEvent.ProximityLeave, cursor)
            else -> error("PenHoverEvent: unknown discriminant ${disc.value}")
        }
    }

    override fun writePenHoverEvent(out: ByteArrayOutputStream, value: PenHoverEvent) {
        when (value) {
            is PenHoverEvent.ProximityEnter -> {
                Bincode.writeEnumDiscriminant(out, 0)
                writePenSample(out, value.value)
            }
            is PenHoverEvent.Move -> {
                Bincode.writeEnumDiscriminant(out, 1)
                writePenSample(out, value.value)
            }
            PenHoverEvent.ProximityLeave -> Bincode.writeEnumDiscriminant(out, 2)
        }
    }

    override fun readPenCapabilities(bytes: ByteArray, offset: Int): Bincode.Decoded<PenCapabilities> {
        var cursor = offset
        val d_pressure = Bincode.readBool(bytes, cursor)
        cursor = d_pressure.consumed
        val pressure = d_pressure.value
        val d_tilt = Bincode.readBool(bytes, cursor)
        cursor = d_tilt.consumed
        val tilt = d_tilt.value
        val d_azimuth = Bincode.readBool(bytes, cursor)
        cursor = d_azimuth.consumed
        val azimuth = d_azimuth.value
        val d_altitude = Bincode.readBool(bytes, cursor)
        cursor = d_altitude.consumed
        val altitude = d_altitude.value
        val d_twist = Bincode.readBool(bytes, cursor)
        cursor = d_twist.consumed
        val twist = d_twist.value
        val d_tangentialPressure = Bincode.readBool(bytes, cursor)
        cursor = d_tangentialPressure.consumed
        val tangentialPressure = d_tangentialPressure.value
        val d_hover = Bincode.readBool(bytes, cursor)
        cursor = d_hover.consumed
        val hover = d_hover.value
        val d_predicted = Bincode.readBool(bytes, cursor)
        cursor = d_predicted.consumed
        val predicted = d_predicted.value
        val d_coalesced = Bincode.readBool(bytes, cursor)
        cursor = d_coalesced.consumed
        val coalesced = d_coalesced.value
        val d_barrelButton = Bincode.readBool(bytes, cursor)
        cursor = d_barrelButton.consumed
        val barrelButton = d_barrelButton.value
        val d_eraser = Bincode.readBool(bytes, cursor)
        cursor = d_eraser.consumed
        val eraser = d_eraser.value
        return Bincode.Decoded(PenCapabilities(pressure = pressure, tilt = tilt, azimuth = azimuth, altitude = altitude, twist = twist, tangentialPressure = tangentialPressure, hover = hover, predicted = predicted, coalesced = coalesced, barrelButton = barrelButton, eraser = eraser), cursor)
    }

    override fun writePenCapabilities(out: ByteArrayOutputStream, value: PenCapabilities) {
        Bincode.writeBool(out, value.pressure)
        Bincode.writeBool(out, value.tilt)
        Bincode.writeBool(out, value.azimuth)
        Bincode.writeBool(out, value.altitude)
        Bincode.writeBool(out, value.twist)
        Bincode.writeBool(out, value.tangentialPressure)
        Bincode.writeBool(out, value.hover)
        Bincode.writeBool(out, value.predicted)
        Bincode.writeBool(out, value.coalesced)
        Bincode.writeBool(out, value.barrelButton)
        Bincode.writeBool(out, value.eraser)
    }

    override fun readPenError(bytes: ByteArray, offset: Int): Bincode.Decoded<PenError> {
        var cursor = offset
        val disc = Bincode.readVarintU64(bytes, cursor)
        cursor = disc.consumed
        return when (disc.value.toInt()) {
            0 -> Bincode.Decoded(PenError.NotAttached, cursor)
            1 -> {
                val d_inner = Bincode.readString(bytes, cursor)
                cursor = d_inner.consumed
                val inner = d_inner.value
                Bincode.Decoded(PenError.Backend(inner) as PenError, cursor)
            }
            else -> error("PenError: unknown discriminant ${disc.value}")
        }
    }

    override fun writePenError(out: ByteArrayOutputStream, value: PenError) {
        when (value) {
            PenError.NotAttached -> Bincode.writeEnumDiscriminant(out, 0)
            is PenError.Backend -> {
                Bincode.writeEnumDiscriminant(out, 1)
                Bincode.writeString(out, value.value)
            }
        }
    }
}
