package dev.istmo.runtime

import kotlinx.coroutines.flow.map

// GENERATED by istmo-build - DO NOT EDIT.
// plugin id: istmo.pen

import java.io.ByteArrayOutputStream

/// Platform-facing surface for the `Pen` plugin. Hand-write an
/// impl with the SDK-specific logic; the dispatcher below handles
/// wire encode/decode.
interface PenBackend {
    fun events(): kotlinx.coroutines.flow.Flow<PenEvent>

    fun hover(): kotlinx.coroutines.flow.Flow<PenHoverEvent>

     // Throw BackendException(PenError) for domain errors.
    suspend fun capabilities(): PenCapabilities

     // Throw BackendException(PenError) for domain errors.
    suspend fun set_prediction_enabled(enabled: Boolean): Unit
}

/// Reader / writer per `Named` type referenced by the `Pen` contract.
/// User provides one impl; each entry typically delegates to a
/// companion helper on the type itself.
interface PenCodecs {
    fun readPenButtonChange(bytes: ByteArray, offset: Int): Bincode.Decoded<PenButtonChange>
    fun writePenButtonChange(out: ByteArrayOutputStream, value: PenButtonChange)

    fun readPenCapabilities(bytes: ByteArray, offset: Int): Bincode.Decoded<PenCapabilities>
    fun writePenCapabilities(out: ByteArrayOutputStream, value: PenCapabilities)

    fun readPenConfig(bytes: ByteArray, offset: Int): Bincode.Decoded<PenConfig>
    fun writePenConfig(out: ByteArrayOutputStream, value: PenConfig)

    fun readPenError(bytes: ByteArray, offset: Int): Bincode.Decoded<PenError>
    fun writePenError(out: ByteArrayOutputStream, value: PenError)

    fun readPenEvent(bytes: ByteArray, offset: Int): Bincode.Decoded<PenEvent>
    fun writePenEvent(out: ByteArrayOutputStream, value: PenEvent)

    fun readPenHoverEvent(bytes: ByteArray, offset: Int): Bincode.Decoded<PenHoverEvent>
    fun writePenHoverEvent(out: ByteArrayOutputStream, value: PenHoverEvent)

    fun readPenMove(bytes: ByteArray, offset: Int): Bincode.Decoded<PenMove>
    fun writePenMove(out: ByteArrayOutputStream, value: PenMove)

    fun readPenSample(bytes: ByteArray, offset: Int): Bincode.Decoded<PenSample>
    fun writePenSample(out: ByteArrayOutputStream, value: PenSample)

    fun readPenToolKind(bytes: ByteArray, offset: Int): Bincode.Decoded<PenToolKind>
    fun writePenToolKind(out: ByteArrayOutputStream, value: PenToolKind)
}

/// Decodes wire calls, invokes `PenBackend`, encodes the response.
/// Register with `IstmoRuntime.registerHandler(PLUGIN_ID, dispatcher)`.
interface PenFactory {
    suspend fun create(config: PenConfig): PenBackend
}

class PenDispatcher(
    private val factory: PenFactory,
    private val codecs: PenCodecs,
) : PluginHandler {

    companion object {
        const val PLUGIN_ID = "istmo.pen"
    }

    private val instances = java.util.concurrent.ConcurrentHashMap<Long, PenBackend>()
    private val nextInstanceId = java.util.concurrent.atomic.AtomicLong(1)

    override suspend fun handleCreateInstance(payload: ByteArray): ByteArray {
        var cursor = 0
        val d_config = codecs.readPenConfig(payload, cursor); cursor = d_config.consumed
        val config = d_config.value
        val backend = factory.create(config)
        val id = nextInstanceId.getAndIncrement()
        instances[id] = backend
        val out = ByteArrayOutputStream()
        Bincode.writeVarintU64(out, id)
        return out.toByteArray()
    }

    override suspend fun handleCall(instanceId: Long, method: String, payload: ByteArray): PluginResult {
        val backend = instances[instanceId]
            ?: error("Pen: unknown instance $instanceId")
        return when (method) {
            "events" -> {
                val __istmo_flow = backend.events()
                PluginResult.Stream(
                    __istmo_flow.map { __istmo_item ->
                        val out = ByteArrayOutputStream()
                        codecs.writePenEvent(out, __istmo_item)
                        out.toByteArray()
                    }
                )
            }
            "hover" -> {
                val __istmo_flow = backend.hover()
                PluginResult.Stream(
                    __istmo_flow.map { __istmo_item ->
                        val out = ByteArrayOutputStream()
                        codecs.writePenHoverEvent(out, __istmo_item)
                        out.toByteArray()
                    }
                )
            }
            "capabilities" -> {
                try {
                    val result = backend.capabilities()
                    val out = ByteArrayOutputStream()
                    codecs.writePenCapabilities(out, result)
                    PluginResult.Unary(out.toByteArray())
                } catch (e: BackendException) {
                    val err = e.error as? PenError ?: throw e
                    val errOut = ByteArrayOutputStream()
                    codecs.writePenError(errOut, err)
                    throw PluginException(errOut.toByteArray())
                }
            }
            "set_prediction_enabled" -> {
                try {
                    var cursor = 0
                    val d_enabled = Bincode.readBool(payload, cursor); cursor = d_enabled.consumed
                    val enabled = d_enabled.value
                    backend.set_prediction_enabled(enabled)
                    PluginResult.Unary(ByteArray(0))
                } catch (e: BackendException) {
                    val err = e.error as? PenError ?: throw e
                    val errOut = ByteArrayOutputStream()
                    codecs.writePenError(errOut, err)
                    throw PluginException(errOut.toByteArray())
                }
            }
            else -> error("unknown Pen method: $method")
        }
    }
}
