package dev.istmo.runtime

import kotlinx.coroutines.flow.map

// GENERATED by istmo-build - DO NOT EDIT.
// plugin id: istmo.pen

data class PenConfig(
    val windowId: ULong
)

enum class PenToolKind {
    Tip,
    Eraser,
    Unknown
}

data class PenSample(
    val x: Float,
    val y: Float,
    val pressure: Float,
    val tiltX: Float,
    val tiltY: Float,
    val azimuth: Float,
    val altitude: Float,
    val twist: Float,
    val tangentialPressure: Float,
    val zOffset: Float,
    val timestampUs: ULong,
    val sequence: UInt,
    val toolId: UInt,
    val toolKind: PenToolKind,
    val buttons: UInt
)

data class PenMove(
    val sample: PenSample,
    val coalesced: List<PenSample>,
    val predicted: List<PenSample>
)

data class PenButtonChange(
    val sample: PenSample,
    val changed: UInt
)

sealed class PenEvent {
    data class Down(val value: PenSample) : PenEvent()
    data class Move(val value: PenMove) : PenEvent()
    data class Up(val value: PenSample) : PenEvent()
    data class Cancel(val value: PenSample) : PenEvent()
    data class ButtonChanged(val value: PenButtonChange) : PenEvent()
}

sealed class PenHoverEvent {
    data class ProximityEnter(val value: PenSample) : PenHoverEvent()
    data class Move(val value: PenSample) : PenHoverEvent()
    object ProximityLeave : PenHoverEvent()
}

data class PenCapabilities(
    val pressure: Boolean,
    val tilt: Boolean,
    val azimuth: Boolean,
    val altitude: Boolean,
    val twist: Boolean,
    val tangentialPressure: Boolean,
    val hover: Boolean,
    val predicted: Boolean,
    val coalesced: Boolean,
    val barrelButton: Boolean,
    val eraser: Boolean
)

sealed class PenError {
    object NotAttached : PenError()
    data class Backend(val value: String) : PenError()
}
